(define (problem path-x-1)
   (:domain path)
   (:objects node1 node2 node3 node4 agenta)
   (:init (node node1)
          (node node2)
          (node node3)
          (node node4)
          (agent agenta)
          (at agenta node1)
          (canTravel node1 node2)
          (canTravel node1 node3)
          (canTravel node2 node4)
          (canTravel node3 node4)
          (= (total-cost) 0)
          (= (travelCost node1 node2) 15)
          (= (travelCost node1 node3) 10)
          (= (travelCost node2 node4) 30)
          (= (travelCost node3 node4) 10)
          )
   (:goal (at agenta node4))
   (:metric minimize (total-cost))
   )
